
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: 'default'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '*.sln'
    #feedsToUse: 'select'
    vstsFeed: '7c696108-0412-4cc7-99f2-1095b0cd371b'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    checkLatest: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    #feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: --no-restore /t:restore
