name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
        
    - name: Restore NuGet packages
      run: nuget restore NTFSPermissions.sln
    
    - uses: warrenbuckley/Setup-MSBuild@v1"
    - run: msbuild NTFSPermissions.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: bin\Release\Publish    
    #- name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 4.7.2
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
